desk/.eslintrc.js
desk/.prettierrc.js
desk/codegen.yml
desk/package.json
desk/yarn.lock

[QCF-3] 프로젝트 setting

---

desk/pages/loginTest/index.tsx

[QCF-4] Test Commit

---

desk/.eslintrc.js
desk/.prettierrc.js
desk/package.json
desk/pages/_app.tsx
desk/yarn.lock

https://qqqcode.atlassian.net/browse/QCF-6?atlOrigin=eyJpIjoiODBmNjY2ZjcyOTU0NDEzZjkwZDg4NWJmYmNjNzExMzQiLCJwIjoiaiJ9

[QCF-6] 컨벤션에 따른 ESLint 적용

---

desk/pages/login/index.tsx
desk/pages/login/signOut/index.tsx
desk/pages/login/signUp/index.tsx

[QCF-10] 로그인 템플릿 생성 및 로그인 작업 환경 구성
[QCF-10]: https://qqqcode.atlassian.net/browse/QCF-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[QCF-10] 로그인 템플릿 생성 및 로그인 작업 환경 구성

---

desk/styles/globalTheme.ts

* theme color 추가
* 기본 내장 네이밍이랑 겹칠수 있기 때문에, 앞에 prefix로 d를 붙혔습니다.

[QCF-21] global color 추가

---

desk/package.json
desk/pages/login/index.tsx
desk/pages/login/logout/index.tsx
desk/pages/login/signOut/index.tsx
desk/pages/login/signUp/index.tsx
desk/pages/login/signup/index.tsx
desk/src/components/units/logIn/Login.container.tsx
desk/src/components/units/logIn/Login.presenter.tsx
desk/src/components/units/logIn/atoms/LoginForm.tsx
desk/src/components/units/logOut/LogOut.container.tsx
desk/src/components/units/logOut/LogOut.presenter.tsx
desk/src/components/units/logOut/atoms/LogOutForm.tsx
desk/src/components/units/signUp/SignUp.container.tsx
desk/src/components/units/signUp/SignUp.presenter.tsx
desk/src/components/units/signUp/atoms/signUpForm.tsx
desk/tsconfig.json
desk/yarn.lock

일단 ui를 만들었습니다.
ui 모양 보시고 피드백 있으면 추가 ui 수정 반영 할 예정
일단 기본 로그인 부터 작동하고, 난 후에 sns 로그인 추가할 예정

[QCF-13] UI 작업 : 로그인 / 회원가입 / 로그아웃

---

desk/package.json
desk/src/commons/libraries/layout/footer/LayoutFooter.container.tsx
desk/src/commons/libraries/layout/footer/LayoutFooter.presenter.tsx
desk/src/commons/libraries/layout/header/LayoutHeader.container.tsx
desk/src/commons/libraries/layout/header/LayoutHeader.presenter.tsx
desk/src/commons/libraries/layout/index.tsx
desk/yarn.lock

- Header (darkmode/user toggle)
- Footer (지금은 로고와 소셜아이콘만 추가해두었습니다.)

Layout 기본 UI 구현

---

desk/pages/user/index.tsx
desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/User.presenter.tsx

[QCF-23] User 페이지 기본 Layout 구현

---

desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/User.presenter.tsx
desk/src/components/units/user/User.types.ts

- 좋아요 기능 추가 (API 나오고 수정 해야함)
- 아이콘 추가 
- 게시글 좋아요, 모아보기 기능추가
- User UI 타입추가

[QCF-36] 유저 페이지 UI 작업

---

desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/User.presenter.tsx
desk/src/components/units/user/User.types.ts
desk/src/components/units/user/components/tabs/Tabs.types.ts
desk/src/components/units/user/components/tabs/index.tsx

- User 페이지 기본 Layout 구현
- Tabs UI 구현
- 성능 개선 리팩토링

[QCF-37] 유저 페이지 UI 작업

---

desk/src/components/units/user/components/followModal/index.tsx

- 유저 페이지 팔로워 / 팔로우 UI 모달로 구현
- API 연결 이후 추가 작업 필요
- 무한스크롤 기능 추가 작업 필요
- 아직 팔로워/팔로우 버튼 클릭 시 모달 창 띄우도록 연결 시켜놓진 않음(나머지 PR 머지 이후에 연결할 계획)

[QCF-47] 유저 페이지 팔로워 / 팔로우 UI 모달 구현

---

desk/package.json
desk/src/components/ui/fileUpload/index.tsx
desk/src/components/units/boards/components/imageUpload/index.tsx
desk/src/components/units/main/categories/best/Best.presenter.tsx
desk/src/components/units/main/categories/recent/Recent.presenter.tsx
desk/src/components/units/main/components/mainBoardSlider/index.tsx
desk/src/components/units/main/components/mainBoardSlider/types.ts
desk/yarn.lock

- 가로스크롤 모듈 개발
- 메인페이지 best / 최근 게시물 카테고리에 가로스크롤 적용
- slick-carousel 라이브러리 설치
- 게시물 등록 페이지 UI 수정
- 메인페이지 모바일 반응형 레이아웃 수정

[QCF-27] 메인페이지 카테고리 가로스크롤 모듈 개발

---

desk/src/components/units/user/User.container.tsx

- 유저 페이지 매직넘버 상수화 
-  useCallback을 사용한 함수 최적화

[QCF-59] 유저페이지 리팩토링 작업

---

desk/pages/boards/[boardId]/index.tsx
desk/pages/boards/index.tsx
desk/src/commons/types/generated/types.ts
desk/src/commons/utils/util.ts
desk/src/components/ui/carousel/index.tsx
desk/src/components/ui/carousel/types.ts
desk/src/components/units/boards/components/itemLinkInput/index.tsx
desk/src/components/units/boards/components/productItemCardList/index.tsx
desk/src/components/units/boards/components/productItemCardList/types.ts
desk/src/components/units/boards/components/profileHeader/index.tsx
desk/src/components/units/boards/components/profileHeader/types.ts
desk/src/components/units/boards/components/tagWithCountState/index.tsx
desk/src/components/units/boards/components/tagWithCountState/types.ts
desk/src/components/units/boards/components/titleWithDescription/index.tsx
desk/src/components/units/boards/components/titleWithInputTags/index.tsx
desk/src/components/units/boards/detail/Detail.container.tsx
desk/src/components/units/boards/detail/Detail.presenter.tsx
desk/src/components/units/boards/detail/Detail.queries.ts
desk/src/components/units/boards/detail/Detail.types.ts

* 게시물 상세 API 적용 (SSR)
* 게시물 상세 UI 적용
* getConvertedDate 유틸 추가

[QCF-34] - 게시물 상세 조회 API

---

desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/User.presenter.tsx
desk/src/components/units/user/components/followModal/index.tsx
desk/src/components/units/user/components/tabs/index.tsx

- 유저 페이지 다크모드 적용
- 팔로워/팔로우 위치 한 줄 소개 위로 변경
- 프로필 변경하기 버튼 마이 페이지에서 팔로우 버튼으로 위치, 크기 변경
- 프로필 변경하기 버튼을 자신의 페이지에서만 보이도록 수정, 다른 페이지에서는 팔로우 버튼으로 변경

[QCF-63] 유저 페이지 UI 수정 & 다크모드 적용

---

desk/pages/accountEdit/index.tsx
desk/src/components/units/accountEdit/components/index.tsx
desk/src/components/units/accountEdit/components/signoutModalButton/index.tsx

- 마이페이지 UI 수정
- 마이페이지 다크모드 적용
- 회원 탈퇴 모달 버튼 파일명, 폴더 변경
- 회원 탈퇴 버튼 색상 변경(빨강 -> 회색)

[QCF-64] 마이 페이지 UI 수정 & 다크모드 적용

---

desk/src/commons/types/generated/types.ts
desk/src/components/units/main/categories/allProducts/AllProducts.container.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.presenter.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.queries.ts
desk/src/components/units/main/categories/allProducts/AllProducts.types.ts
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.container.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.presenter.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.queries.ts
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.types.ts

- 전체장비 모아보기 카테고리 타입 수정 / 데이터 주입 / api 연결
- 전체장비 모아보기 더보기 페이지 타입 수정 / 데이터 주입 / api 연결
- code generate

[QCF-56] 사용 장비모아보기 api 연결

---

desk/.eslintrc.js

Develop - ESLint Rollback

---

desk/pages/auth/index.tsx
desk/pages/auth/login/index.tsx
desk/pages/auth/logout/index.tsx
desk/pages/auth/signout/index.tsx
desk/pages/auth/signup/index.tsx
desk/src/components/units/auth/login/components/LoginForm.tsx
desk/src/components/units/auth/signout/components/signoutForm.tsx

완료 / 타입스크립트 오류나는 부분 수정 > LoginForm.tsx
완료 / pages eslit적용 + prettier적용 / 그 외 에러처리

[QCF-57] 유저인증 파트 / 기능개선

---

desk/src/components/units/user/components/tabs/Tabs.queries.ts
desk/src/components/units/user/components/tabs/index.tsx

- fetchProducts -> fetchUserProducts API 변경

[QCF-75] 변경 API 적용

---

desk/src/components/units/boards/components/itemLinkInput/OpenGraphPreview.tsx
desk/src/components/units/boards/components/itemLinkInput/index.tsx
desk/src/components/units/boards/components/itemLinkInput/queries.ts
desk/src/components/units/boards/components/itemLinkInput/types.ts
desk/src/components/units/boards/components/productItemCardList/index.tsx
desk/src/components/units/boards/detail/Detail.presenter.tsx
desk/src/components/units/boards/detail/Detail.queries.ts
desk/src/components/units/boards/register/Register.container.tsx

* 게시물 등록에 장비 등록 onBlur시 og preview ui 로직 추가

[QCF-71] - 게시물 등록에 변경된 OG API 수정

---

desk/package.json
desk/src/commons/hooks/useAuth.tsx
desk/src/commons/store/atom.ts
desk/src/components/units/auth/login/components/LoginForm.tsx
desk/yarn.lock

완료 / 로그인시 아이디 저장하기 기능
> localStorage 이용 할려고 다시 재설치 하였습니다. recoil-persist
완료 / 마지막 로그인 표시

[QCF-78] - 유저인증 / 로그인 오류 개선

---

desk/src/commons/hooks/useAuth.tsx
desk/src/commons/libraries/layout/header/LayoutHeader.presenter.tsx
desk/src/commons/store/atom.ts
desk/src/components/units/auth/login/components/LoginForm.tsx
desk/src/components/units/auth/queries/mutation.ts

로그인
* 팝업 > 간격 고정
* 저장하기 클릭시 저장됨
* 마지막 로그인 버튼 디폴트값으로 변경
프로필
* 팔로우 팔로잉 메뉴 표시

[QCF-85] <유저인증 / 추가개선>

---

desk/src/commons/libraries/layout/header/LayoutHeader.presenter.tsx
desk/src/components/units/auth/login/components/LoginForm.tsx
desk/src/components/units/main/viewMore/recentMore/RecentMore.presenter.tsx

완료 / 프로필에 닉네임 뜨기
완료 / 로그인SNS버튼 > 심플그리드 적용 완료

[QCF-86] <유저인증 / 추가개선>

---

desk/src/commons/libraries/layout/header/LayoutHeader.presenter.tsx
desk/src/commons/types/generated/types.ts
desk/src/components/units/boards/components/countStateWithLike/index.tsx
desk/src/components/units/boards/components/detailBoardImages/index.tsx
desk/src/components/units/boards/components/profileHeader/index.tsx
desk/src/components/units/boards/components/titleWithInputTags/index.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.container.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.presenter.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.queries.ts
desk/src/components/units/main/categories/allProducts/AllProducts.types.ts
desk/src/components/units/main/categories/youtube/Youtube.presenter.tsx
desk/src/components/units/main/components/categoryHeader/CategoryHeader.presenter.tsx
desk/src/components/units/main/components/mainBoardSlider/index.tsx
desk/src/components/units/main/components/searchBoards/SearchBoards.container.tsx
desk/src/components/units/main/components/searchBoards/SearchBoards.presenter.tsx
desk/src/components/units/main/components/youtubeSlider/index.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.container.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.presenter.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.queries.ts
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.types.ts
desk/src/components/units/main/viewMore/followingBoardsMore/FollowingBoardsMore.presenter.tsx
desk/src/components/units/main/viewMore/recentMore/RecentMore.presenter.tsx
desk/styles/globalTheme.ts

- 검색 결과 모달창 계속 뜨는 버그 수정
- fetchAllProducts api 수정 - 쿼리 변경
- 사용장비 클릭 시 제품을 소개한 상세페이지로 라우팅
- css sx로 변경
- 유튜브 제목 크기 조정
- 모바일 시 게시물 간격 좁게 수정
- 카테고리헤더 더보기 컬러 변경
- 검색 결과 모달창 화면 가운데 위치하도록 수정
- 폰트 추가
- 헤더 토글 프로필 UI 수정
- Avatar name 속성 추가 / 모바일 UI 수정
- 게시물 삭제 확인 모달 추가
- 게시물 상세페이지 수정버튼, 간격, 아바타 UI 수정
- 게시물 상세페이지 좋아요 버튼 아이콘 변경
- 조회수 formatNumber util 사용
- 게시물 등록 해시태그 input 다크모드 컬러 변경

[QCF-83] 메인페이지 추가 리팩토링 / 전체 UI 세부 수정

---

desk/src/commons/hooks/useAuth.tsx

로그아웃시 아바타 프로필 변경 / 하트표시 그대로 남는 오류 개선

[QCF-90] 로그아웃 새로고침

---

desk/src/commons/types/generated/types.ts
desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/components/followModal/FollowModal.queries.ts
desk/src/components/units/user/components/followModal/index.tsx

- 유저페이지 팔로워/팔로우 쿼리 수정 
- 유저페이지 팔로워/팔로우 수 받아오는 동안 undefined -> 0으로 수정

[QCF-91] 팔로워/팔로우 쿼리 수정 적용

---

desk/pages/404.tsx
desk/pages/_error.tsx

[QCF-97] - 에러페이지 개발

---

desk/src/commons/libraries/layout/header/LayoutHeader.presenter.tsx
desk/src/components/ui/logo/index.tsx
desk/src/components/units/boards/components/productItemCardList/index.tsx
desk/src/components/units/boards/components/profileHeader/index.tsx
desk/src/components/units/boards/detail/Detail.presenter.tsx
desk/src/components/units/main/components/searchBoards/SearchBoards.presenter.tsx

* 모바일 상세화면
* 수정, 삭제 버튼 깨지는 이슈 수정 
* 타이틀 길때 Quote 이미지 깨지는 이슈 수정
* 사용중인장비 UI columns 변경
* 모바일시 헤더 로고, 버튼 사이즈 줄임

[QCF-7] 상세 및 헤더 모바일 대응 이슈 수정

---

desk/src/components/units/accountEdit/AccountEdit.container.tsx
desk/src/components/units/accountEdit/AccountEdit.presenter.tsx
desk/src/components/units/accountEdit/AccountEdit.types.ts
desk/src/components/units/accountEdit/components/signoutModalButton/index.tsx
desk/src/components/units/accountEdit/components/snsAccountEdit/index.tsx
desk/src/components/units/accountEdit/components/snsAccountEdit/types.ts
desk/src/components/units/auth/Auth.types.ts
desk/src/components/units/auth/queries/mutation.ts
desk/src/components/units/auth/signup/components/MyJobSelect.tsx
desk/src/components/units/user/User.container.tsx
desk/src/components/units/user/User.presenter.tsx
desk/src/components/units/user/components/followModal/index.tsx
desk/src/components/units/user/components/productItem/index.tsx
desk/src/components/units/user/components/snsAccount/index.tsx
desk/src/components/units/user/components/tabs/index.tsx

- 유저페이지 모바일 대응
- 프로필 수정 페이지  모바일 대응

[QCF-96] 모바일 대응

---

desk/src/commons/utils/util.ts
desk/src/components/units/accountEdit/AccountEdit.presenter.tsx
desk/src/components/units/boards/components/productItemCardList/index.tsx
desk/src/components/units/main/categories/allProducts/AllProducts.presenter.tsx
desk/src/components/units/main/categories/youtube/Youtube.presenter.tsx
desk/src/components/units/main/components/categoryHeader/CategoryHeader.types.ts
desk/src/components/units/main/components/mainBoardSlider/index.tsx
desk/src/components/units/main/components/mainProductItems/index.tsx
desk/src/components/units/main/components/userProfileCard/index.tsx
desk/src/components/units/main/components/youtubeSlider/index.tsx
desk/src/components/units/main/viewMore/allProductsMore/AllProductsMore.presenter.tsx
desk/src/components/units/main/viewMore/jobGroupMore/JobGroupMore.container.tsx
desk/src/components/units/main/viewMore/jobGroupMore/JobGroupMore.presenter.tsx
desk/src/components/units/user/User.presenter.tsx

- 직군 탭 전체 순서 변경
- 직군 뱃지 컬러 변경
- 직군 탭 모바일 환경 iconMapping 추가
- util JOB_LIST 미포함 직군 추가
- 직군 뱃지 UI 통일
- 유튜브 카테고리 아이콘 추가
- slider infinite 속성 변경
- 사용 장비 더보기 UI 수정
- 사용 중인 장비 모바일 폰트사이즈 변경
- 장비 카테고리 slider 수정

[QCF-101] 프로필 탭 수정
